name: termenv
description: Advanced styling for terminal emulators
version: 0.0.1
repository: https://github.com/Thesmader/termenv

platforms:
  linux:
  macos:

environment:
  sdk: ^3.1.4

dependencies:
  color_models: ^1.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
